<header class="navbar navbar-expand-md navbar-dark bd-navbar mb-4">
    <nav class="container-xxl flex-wrap flex-md-nowrap">
        <div class="collapse navbar-collapse" id="bdNavbar">
            <ul class="navbar-nav flex-row flex-wrap bd-navbar-nav pt-2 py-md-0">
                <li class="nav-item col-6 col-md-auto">
                    <?php echo $this->tag->linkTo(["/", "Home", 'class' => 'nav-link']);?>
                </li>

                <?php if(!$this->auth->getUser()->id){?>
                    <li class="nav-item col-6 col-md-auto">
                        <?php echo $this->tag->linkTo(["registration", "Registration", 'class' => 'nav-link']);?>
                    </li>
                <?php } ?>

                <?php if(!$this->auth->getUser()->id){?>
                    <li class="nav-item col-6 col-md-auto">
                        <?php echo $this->tag->linkTo(["login", "LogIn", 'class' => 'nav-link']);?>
                    </li>
                <?php } ?>

                <li class="nav-item col-6 col-md-auto">
                    <?php echo $this->tag->linkTo(["abc", "404 Page", 'class' => 'nav-link']);?>
                </li>

                <?php if($this->auth->getUser()->id){?>
                    <li class="nav-item col-6 col-md-auto">
                        <?php echo $this->tag->linkTo(["admin", "Admin", 'class' => 'nav-link']);?>
                    </li>
                <?php } ?>

                <?php if($this->auth->getUser()->id){?>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Users manager
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="/admin/user/create">Create</a></li>
                        </ul>
                    </li>
                <?php } ?>
            </ul>
            <?php if($this->auth->getUser()->id){
                echo $this->tag->linkTo(["logout", "Logout", 'class' => 'btn btn-bd-download ms-md-auto']);
            } ?>
        </div>
    </nav>
</header>