<?php if ($users->count() > 0) {?>
    <table class="table table-striped table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>
                Name
                <a href="<?php echo $listHelper->getSortLink('name');?>">
                    <i class="bi bi-sort-<?php if($orderby == 'name'){echo ($order == 'DESC') ? 'up' : 'down-alt';} else {echo 'down-alt';}?>"></i>
                </a>
            </th>
            <th>
                Email
                <a href="<?php echo $listHelper->getSortLink('email');?>">
                    <i class="bi bi-sort-<?php if($orderby == 'email'){echo ($order == 'DESC') ? 'up' : 'down-alt';} else {echo 'down-alt';}?>"></i>
                </a>
            </th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}

echo $this->partial("partials/pagination");