<?php if ($users->count() > 0) {?>
    <form method="GET" class="row g-3 align-items-center">
        <div class="col-auto">
            <label for="inputPassword6" class="col-form-label">Search</label>
        </div>
        <div class="col-auto">
            <input type="text" name="search[]['name']" id="search_name" class="form-control" aria-describedby="passwordHelpInline">
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-bd-light">Search</button>
        </div>
    </form>

    <table class="table table-striped table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>
                Name
                <a href="<?php echo $listHelper->getSortLink('name');?>">
                    <i class="bi bi-sort-<?php if($orderby == 'name'){echo ($order == 'DESC') ? 'up' : 'down-alt';} else {echo 'down-alt';}?>"></i>
                </a>
            </th>
            <th>
                Email
                <a href="<?php echo $listHelper->getSortLink('email');?>">
                    <i class="bi bi-sort-<?php if($orderby == 'email'){echo ($order == 'DESC') ? 'up' : 'down-alt';} else {echo 'down-alt';}?>"></i>
                </a>
            </th>
            <?php if($this->auth->getUser()->id){?>
                <th>Actions</th>
            <?php } ?>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
                <?php if($this->auth->getUser()->id){?>
                    <td>
                        <?php echo $this->tag->linkTo(["/admin/user/{$user->id}/edit", "edit", 'class' => 'nav-link']);?>
                    </td>
                <?php } ?>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}

echo $this->partial("partials/pagination");