<?php if ($permissions->count() > 0) {?>
    <table class="table table-striped table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>
                Name
                <a href="<?php echo $listHelper->getSortLink('action');?>">
                    <i class="bi bi-sort-<?php if($orderby == 'action'){echo ($order == 'DESC') ? 'up' : 'down-alt';} else {echo 'down-alt';}?>"></i>
                </a>
            </th>
            <?php if($this->auth->getUser()->id){?>
                <th>Actions</th>
            <?php } ?>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Permissions quantity: <?php echo $permissions->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($permissions as $permission) { ?>
            <tr>
                <td><?php echo $permission->id; ?></td>
                <td><?php echo $permission->action; ?></td>
                <?php if($this->auth->getUser()->id){?>
                    <td>
                        <?php echo $this->tag->linkTo(["/admin/user/{$permission->id}/edit", "edit", 'class' => 'nav-link']);?>
                    </td>
                <?php } ?>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}

echo $this->partial("partials/pagination");